### ISSUE TITLE
Having trouble building the project

### ISSUE THREAD

**Issue by sourabhmarathe** [osu-crypto/BaRK-OPRF#1]
I am having trouble with the mpir dependency and was wondering if you had run into this issue previously. When I run `make`, I get the following output: 
`g++ -ggdb -ffunction-sections -O3 -Wall -std=c++11 -maes -msse2 -msse4.1 -mpclmul -Wfatal-errors -pthread -Wno-narrowing  -I./bOPRFlib -I./thirdparty/linux -I./thirdparty/linux/boost/includes -I./thirdparty/linux/miracl -I./thirdparty/linux/mpir -I./thirdparty/linux/cryptopp -std=c++11  -DNDEBUG -DRELEASE -c bOPRFlib/Common/ByteStream.cpp -o Release/./bOPRFlib/Common/ByteStream.o -MD -MF Release/./bOPRFlib/Common/ByteStream.dep
In file included from ./bOPRFlib/OT/Base/Math/modp.h:17:0,
                 from ./bOPRFlib/Crypto/PRNG.h:2,
                 from ./bOPRFlib/Crypto/Commit.h:5,
                 from bOPRFlib/Common/ByteStream.cpp:5:
./bOPRFlib/OT/Base/Math/bigint.h:14:25: fatal error: mpir/mpirxx.h: No such file or directory
 #include "mpir/mpirxx.h"
                         ^
compilation terminated.
make: *** [Release/./bOPRFlib/Common/ByteStream.o] Error 1`

**Comment by ladnir** [comment]
Unless you are wanting to compare against this protocol, you will likely be better off using this (optimized) implementation https://github.com/osu-crypto/libOTe/tree/master/libOTe/NChooseOne/Kkrt

**Comment by sourabhmarathe** [comment]
Thank you for responding. I have a broader question with regards to this repo and the link provided - is it possible to use those OPRFs as primitives within a larger protocol? Additionally, would I be able to generate keys modularly, and have entities submit their own inputs to a given OPRF?

**Comment by ladnir** [comment]
You can use either repo in a larger protocol, libOTe is more maintained though.

The security of these protocols are in the two party settings. The keys have to be chosen at random (an interactive process between the parties samples the keys at random). Once the keys are sample, the "receiver" can learn a single oprf value f(k_i,...) for each key k_i. The "sender" can learn all oprf outputs for all they keys.

Anyone can play the role of sender and receiver.

**Comment by nitrieu** [comment]
The compile issue is because of "mpir/mpirxx.h: No such file or directory". I suggest that you might manually follow each command in https://github.com/osu-crypto/BaRK-OPRF/blob/master/thirdparty/linux/mpir.get

If you just want BaRK-OPRF, I recommend you to use libOTe which has a better interface + optimization. 

Note that both libOTe/kkrt and this repo only give you a relaxation of OPRF with related keys! Concretely, the keys (as a sender holds) are related to receiver's inputs. It is important thing that is different from the traditional/original OPRF described in https://www.iacr.org/cryptodb/archive/2005/TCC/3657/3657.pdf

**Comment by sourabhmarathe** [comment]
Thank you for responding. I am going to go with trying to build libOTe based on your advice.
